image:
  file: .gitpod.dockerfile
ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - init: >
      rvm install 2.6.5 &&
      rvm use 2.6.5 --default &&
      gem install bundler -v '1.17.3' &&
      bundle install --without production &&
      overcommit --install &&
      rails db:migrate dev:setup
    command: >
      rails s
vscode:
  extensions:
    - rebornix.ruby@0.25.0:bXAxc7TXjSgttjLHFnpmVg==
    - connorshea.vscode-ruby-test-adapter@0.6.1:HO9rpcRv7bmRIuo7Mty/zg==
    - hbenl.vscode-test-explorer@2.15.0:koqDUMWDPJzELp/hdS/lWw==
    - misogi.ruby-rubocop@0.8.3:ptn+lTc9xnktGhPEYKIf2w==