gemfile: Gemfile

PreCommit:
  BrokenSymlinks:
    enabled: false

  BundleCheck:
    enabled: true

  ExecutePermissions:
    enabled: true
    exclude:
      - 'bin/*'
      - 'libexec/**/*'
      - 'template-dir/hooks/**/*'

  HardTabs:
    enabled: true

  MasterHooksMatch:
    enabled: true
    quiet: true

  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop']
    include:
      - '**/*.gemspec'
      - '**/*.rb'
      - '**/Gemfile'
      - template-dir/hooks/overcommit-hook

  TrailingWhitespace:
    enabled: true

  YamlSyntax:
    enabled: true