unit Test.Services.Events;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, FireDAC.Comp.Client, SysUtils, Services.Events, Ragna, System.JSON,
  Providers.Connection, Data.DB;

type
  // Test methods for class TServiceEvents

  TestTServiceEvents = class(TTestCase)
  strict private
    FServiceEvents: TServiceEvents;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestGetNextEvents;
    procedure TestGetEvent;
    procedure TestPostEvent;
  end;

implementation

procedure TestTServiceEvents.SetUp;
begin
  FServiceEvents := TServiceEvents.Create;
  Writeln('');
end;

procedure TestTServiceEvents.TearDown;
begin
  FServiceEvents.Free;
  FServiceEvents := nil;
end;

procedure TestTServiceEvents.TestGetNextEvents;
var
  JSON: TJSONArray;
  sFilter: string;
  ReturnValue: string;
begin
  Write('Test get next events');
  sFilter := 'date > date(' + 'now'.QuotedString + ')';
  FServiceEvents.Get(sFilter).ToJson(JSON);
  ReturnValue := JSON.ToJSON;
  Check(not ReturnValue.IsEmpty);
  Writeln(' - OK');
end;

procedure TestTServiceEvents.TestGetEvent;
var
  ReturnValue: TFDQuery;
  nId: Integer;
begin
  nId := 1;
  Write('Test get event ' + nId.ToString.QuotedString);
  ReturnValue := FServiceEvents.Get(nId);
  Check(not ReturnValue.IsEmpty);
  Writeln(' - OK');
end;

procedure TestTServiceEvents.TestPostEvent;
const
  ID = 999;
var
  ReturnValue: TFDQuery;
  Event: TJSONObject;
begin
  Write('Test post event ' + ID.ToString.QuotedString);
  Event := TJSONObject.Create;
  try
    Event.AddPair('description', TJSONString.Create('any_event'));
    Event.AddPair('date', TJSONString.Create('2020-02-02'));

    ReturnValue := FServiceEvents.Post(ID, Event);
    ReturnValue.Filter := 'id=' + ID.ToString;
    ReturnValue.Filtered := True;
    CheckFalse(ReturnValue.IsEmpty);
    ReturnValue.Delete;
    Writeln(' - OK');
  finally
    FreeAndNil(Event);
  end;
end;

initialization
  RegisterTest(TestTServiceEvents.Suite);
end.

